### ISSUE TITLE
May I reproduce Figure 1 in jfcrenshaw/pzflow-paper?

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork-paper#1]

**Comment by jfcrenshaw** [comment]
If this is a request for permission, the answer is yes!

**Comment by rodluger** [comment]
I'm getting trauma from 11th grade English class now... Yes, I meant "may". Thanks!

**Comment by jfcrenshaw** [comment]
Haha I wasn't sure if you were just seeing if you could! 😂
