### ISSUE TITLE
May I reproduce Table 1 in dfm/araa-gps?

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork-paper#2]

**Comment by dfm** [comment]
I dunno - can you?

**Comment by rodluger** [comment]
Har har!

**Comment by dfm** [comment]
ARA&A may own the copyright… not entirely sure! What's the context?

**Comment by rodluger** [comment]
I wanted to both showcase a dynamically generated table and advertise your paper as a use case of showyourwork:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/9323819/192630285-531960f7-823a-4663-bcf9-d79f64bc0846.png">

but can certainly choose a different table for this.

**Comment by dfm** [comment]
Oh I see it now. I think it's probably fine if you just say "adapted from" or "based on" since we didn't use this method in our paper!

**Comment by rodluger** [comment]
Ok will do! Thanks!
